graph:
  vertices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
  edges:
    - { src: 0, dst: 1, wt: 1.0, dir: False }
    - { src: 0, dst: 1, wt: 1.0, dir: False }
    - { src: 0, dst: 7, wt: 1.0, dir: False }
    - { src: 0, dst: 9, wt: 1.0, dir: False }
    - { src: 0, dst: 11, wt: 1.0, dir: False }
    - { src: 1, dst: 8, wt: 1.0, dir: False }
    - { src: 1, dst: 10, wt: 1.0, dir: False }
    - { src: 2, dst: 3, wt: 1.0, dir: False }
    - { src: 2, dst: 12, wt: 1.0, dir: False }
    - { src: 3, dst: 4, wt: 1.0, dir: False }
    - { src: 3, dst: 7, wt: 1.0, dir: False }
    - { src: 5, dst: 6, wt: 1.0, dir: False }
    - { src: 6, dst: 7, wt: 1.0, dir: False }
    - { src: 7, dst: 11, wt: 1.0, dir: False }
    - { src: 8, dst: 9, wt: 1.0, dir: False }
    - { src: 8, dst: 12, wt: 1.0, dir: False }
    - { src: 9, dst: 10, wt: 1.0, dir: False }
