graph:
  vertices: [0, 1, 2, 3, 4, 5, 6]
  edges:
    - { src: 0, dst: 1, wt: 2.0, dir: True }
    - { src: 0, dst: 2, wt: 5.0, dir: True }
    - { src: 0, dst: 6, wt: 10.0, dir: True }
    - { src: 1, dst: 2, wt: 2.0, dir: True }
    - { src: 1, dst: 4, wt: 11.0, dir: True }
    - { src: 2, dst: 6, wt: 2.0, dir: True }
    - { src: 4, dst: 5, wt: 1.0, dir: True }
    - { src: 5, dst: 4, wt: -2.0, dir: True }
    - { src: 6, dst: 5, wt: 11.0, dir: True }
