graph:
  vertices: [0, 1, 2, 3, 4, 5, 6, 7]
  edges:
    - { src: 0, dst: 1, wt: 3.0, dir: True }
    - { src: 0, dst: 2, wt: 6.0, dir: True }
    - { src: 1, dst: 2, wt: 4.0, dir: True }
    - { src: 1, dst: 3, wt: 4.0, dir: True }
    - { src: 1, dst: 4, wt: 11.0, dir: True }
    - { src: 2, dst: 3, wt: 8.0, dir: True }
    - { src: 2, dst: 6, wt: 11.0, dir: True }
    - { src: 3, dst: 4, wt: -4.0, dir: True }
    - { src: 3, dst: 5, wt: 5.0, dir: True }
    - { src: 3, dst: 6, wt: 2.0, dir: True }
    - { src: 4, dst: 7, wt: 9.0, dir: True }
    - { src: 5, dst: 7, wt: 1.0, dir: True }
    - { src: 6, dst: 7, wt: 2.0, dir: True }
